# Generated by Django 6.0.2 on 2026-02-19 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, help_text='Например: +79991234567', max_length=15, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, help_text='Адрес для бесплатной доставки вещей на склад', verbose_name='Адрес доставки')),
                ('avatar', models.ImageField(blank=True, help_text='Изображение профиля (рекомендуемый размер 200x200px)', null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('pdn_accepted', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код доступа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-created_at'],
            },
        ),
    ]
