# Generated by Django 6.0.2 on 2026-02-18 08:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Адрес склада"),
                ),
                (
                    "ceiling_height",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Высота потолка (м)",
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость одного места (руб.)",
                    ),
                ),
                (
                    "unit_size_category",
                    models.CharField(
                        choices=[
                            ("small", "До 3 м²"),
                            ("medium", "До 10 м²"),
                            ("large", "От 10 м²"),
                        ],
                        max_length=10,
                        verbose_name="Категория размера места",
                    ),
                ),
                (
                    "total_units",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Общее количество мест"
                    ),
                ),
                (
                    "occupied_units",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество занятых мест"
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
                "ordering": ["address"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Адрес клиента"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "required_units",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество занятых мест"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь (Личный кабинет)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["full_name"],
            },
        ),
    ]
