# Generated by Django 6.0.2 on 2026-02-18 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="rent_end_date",
            field=models.DateField(
                blank=True,
                help_text="Планируемая дата освобождения места. Оставьте пустым для бессрочной аренды.",
                null=True,
                verbose_name="Дата окончания аренды",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="rent_start_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Дата, с которой начинается оплата и использование места.",
                verbose_name="Дата начала аренды",
            ),
        ),
    ]
