# Generated by Django 6.0.2 on 2026-02-18 08:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_client_rent_end_date_client_rent_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="contacts",
            field=models.TextField(blank=True, verbose_name="Контакты склада"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание склада"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="directions",
            field=models.TextField(blank=True, verbose_name="Инструкция по проезду"),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="temperature",
            field=models.CharField(
                default="17 °С",
                help_text="Например: 17 °С или 15-20 °С",
                max_length=50,
                verbose_name="Температурный режим",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="rent_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания аренды"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="rent_start_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата начала аренды"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="WarehouseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="warehouses/", verbose_name="Изображение"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="storage.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография склада",
                "verbose_name_plural": "Фотографии складов",
                "ordering": ["order"],
            },
        ),
    ]
