# Generated by Django 6.0.2 on 2026-02-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_warehouse_contacts_warehouse_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="town",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Расположение"
            ),
        ),
    ]
