# Generated by Django 6.0.2 on 2026-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_warehouse_town"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="town",
            field=models.CharField(max_length=255, verbose_name="Расположение"),
        ),
    ]
