# Generated by Django 6.0.2 on 2026-02-18 12:22

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_alter_warehouse_town"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="rent_end_date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="rent_start_date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="required_units",
        ),
        migrations.CreateModel(
            name="RentalAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "units_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество мест",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=datetime.date.today, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Оставьте пустым для бессрочной аренды",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("complited", "Завершен"),
                            ("canceled", "Завершен"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="storage.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements",
                        to="storage.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Договор аренды",
                "verbose_name_plural": "Договоры аренды",
                "ordering": ["-created_at"],
            },
        ),
    ]
