# Generated by Django 6.0.2 on 2026-02-18 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_remove_client_rent_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalagreement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Оставьте пустым для бессрочной аренды",
                null=True,
                verbose_name="Дата окончания",
            ),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="start_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("completed", "Завершен"),
                    ("cancelled", "Завершен"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
