# Generated by Django 6.0.2 on 2026-02-19 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0007_alter_rentalagreement_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="cost_per_unit",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="occupied_units",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="total_units",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="unit_size_category",
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="ceiling_height",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                verbose_name="Высота потолка всего зала (м)",
            ),
        ),
        migrations.CreateModel(
            name="BoxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Длина (м)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Ширина (м)",
                    ),
                ),
                (
                    "heigth",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Высота (м)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        verbose_name="Объем (м³)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("small", "До 3м³"),
                            ("medium", "До 10м³"),
                            ("large", "Свыше 10м³"),
                        ],
                        editable=False,
                        max_length=10,
                        verbose_name="Категория объема",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость аренды (руб/мес)",
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("occupied_count", models.PositiveIntegerField(default=0)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_types",
                        to="storage.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип бокса",
                "verbose_name_plural": "Типы боксов",
                "ordering": ["volume"],
            },
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="box_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="storage.boxtype",
                verbose_name="Тип бокса",
            ),
        ),
    ]
