# Generated by Django 6.0.2 on 2026-02-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0008_remove_warehouse_cost_per_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalagreement",
            name="box_type",
        ),
    ]
