# Generated by Django 6.0.2 on 2026-02-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_remove_rentalagreement_box_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boxtype",
            old_name="heigth",
            new_name="height",
        ),
    ]
