# Generated by Django 6.0.2 on 2026-02-19 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_rename_heigth_boxtype_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalagreement",
            name="box_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите тип бокса",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreements",
                to="storage.boxtype",
                verbose_name="Тип бокса",
            ),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="units_count",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество мест",
            ),
        ),
    ]
