# Generated by Django 6.0.2 on 2026-02-19 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0011_rentalagreement_box_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "ordering": ["town", "address"],
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.RemoveField(
            model_name="boxtype",
            name="occupied_count",
        ),
        migrations.RemoveField(
            model_name="boxtype",
            name="total_count",
        ),
        migrations.RemoveField(
            model_name="rentalagreement",
            name="box_type",
        ),
        migrations.RemoveField(
            model_name="rentalagreement",
            name="units_count",
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="rentalagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="Номер бокса")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Свободен"),
                            ("occupied", "Занят"),
                            ("maintenance", "На обслуживании"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "box_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="storage.boxtype",
                        verbose_name="Тип бокса",
                    ),
                ),
                (
                    "current_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boxes_rented",
                        to="storage.rentalagreement",
                        verbose_name="Текущий договор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бокс",
                "verbose_name_plural": "Боксы",
                "ordering": ["number"],
                "unique_together": {("box_type", "number")},
            },
        ),
        migrations.AddField(
            model_name="rentalagreement",
            name="boxes",
            field=models.ManyToManyField(
                blank=True,
                related_name="agreements",
                to="storage.box",
                verbose_name="Арендуемые боксы",
            ),
        ),
    ]
