# Generated by Django 6.0.2 on 2026-02-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0012_alter_warehouse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxtype",
            name="occupied_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boxtype",
            name="total_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
