# Generated by Django 6.0.2 on 2026-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0013_boxtype_occupied_count_boxtype_total_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalagreement",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
    ]
