# Generated by Django 6.0.2 on 2026-02-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0014_alter_rentalagreement_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        help_text="ID сессии пользователя",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("yandex", "Яндекс.Директ"),
                            ("google", "Google Ads"),
                            ("vk", "VK Реклама"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=50,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Тип трафика (utm_medium)",
                    ),
                ),
                (
                    "campaign",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Компания (utm_campaign)",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Ключевое слово (utm_term)",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Контент (utm_content)"
                    ),
                ),
                ("landing_page", models.URLField(verbose_name="Страница входа")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата перехода"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_transitions",
                        to="storage.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекламный переход",
                "verbose_name_plural": "Рекламные переходы",
                "ordering": ["-created_at"],
            },
        ),
    ]
