# Generated by Django 6.0.2 on 2026-02-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0015_adtransition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                    ("overdue", "Просрочен"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
