# Generated by Django 6.0.2 on 2026-02-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_alter_rentalagreement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
