# Generated by Django 6.0.2 on 2026-02-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='grace_period_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление о льготном периоде отправлено'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='last_overdue_reminder_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего напоминания о просрочке'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление о просрочке отправлено'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='reminder_14d_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание за 14 дней отправлено'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='reminder_30d_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание за 30 дней отправлено'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='reminder_3d_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание за 3 дня отправлено'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='reminder_7d_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание за 7 дней отправлено'),
        ),
    ]
