# Generated by Django 6.0.2 on 2026-02-22 18:17

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_rentalagreement_grace_period_notification_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код для ввода пользователем', max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_percent', models.PositiveIntegerField(help_text='Размер скидки в процентах (от 1 до 100)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Скидка (%)')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Сколько раз можно применить этот промокод (0 - без ограничений)', verbose_name='Максимальное количество использований')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, help_text='Оставьте пустым для бессрочного действия', null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='storage.promocode', verbose_name='Примененный промокод'),
        ),
    ]
