# Generated by Django 6.0.2 on 2026-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_promocode_rentalagreement_promo_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rentalagreement',
            constraint=models.UniqueConstraint(fields=('client', 'promo_code'), name='unique_client_promo'),
        ),
    ]
