# Generated by Django 6.0.2 on 2026-02-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_rentalagreement_unique_client_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalagreement',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Бесплатный вывоз'),
        ),
    ]
