# Generated by Django 6.0.2 on 2026-02-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_rentalagreement_free_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-02-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID для уведомлений', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_linked',
            field=models.BooleanField(default=False, help_text='Telegram привязан к аккаунту'),
        ),
    ]
